# Етап 1: Збірка (Build) 
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Копіюємо файл проекту та відновлюємо залежності
COPY ["GameShop.csproj", "./"]
RUN dotnet restore "GameShop.csproj"

# Копіюємо весь інший код і робимо publish
COPY . .
RUN dotnet publish "GameShop.csproj" -c Release -o /app/publish

# Етап 2: Запуск (Run)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Вказуємо порт, на якому працюватиме додаток всередині контейнера
EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080

ENTRYPOINT ["dotnet", "GameShop.dll"]
